# Use postgres/example user/password credentials
version: '3.3'

networks:
  netpostgres:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
         - ./DB/pg-data:/var/lib/postgresql/data
         - ./DB/backups:/var/lib/postgresql/backups
    ports:
         - 15432:5432
    networks:
       netpostgres:
           ipv4_address: 172.20.0.7
  pgadmin:
    image: dpage/pgadmin4
    environment:
       PGADMIN_DEFAULT_EMAIL: "jonataneduardo777@gmail.com"
       PGADMIN_DEFAULT_PASSWORD: "jonatan687251"
       PGADMIN_LISTEN_PORT: 80
    volumes:
        - ./PGA4/pgAdmin4:/var/lib/pgadmin/data
    ports:
        - "8080:80"
    networks:
       netpostgres:
           ipv4_address: 172.20.0.10
    depends_on:
      - db
                  
         